export type ExtractedMetrics = {
  sprintTime?: number;
  accelerationTiming?: number;
  changeOfDirectionMeasurement?: number;
  shotTiming?: number;
  repetitionCount?: number;
  motionTrackingScore?: number;
  frameBasedDuration?: number;
  errorToleranceScore?: number;
  drillCompletionRate?: number;
  consistencyScore?: number;
  reliabilityScore?: number;
  speed?: number;
  acceleration?: number;
  agilityScore?: number;
  techniqueScore?: number;
  accuracyScore?: number;
  powerScore?: number;
  overallPerformanceScore?: number;
};
